//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezgıelıfproje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COOKSGRAMEntities : DbContext
    {
        public COOKSGRAMEntities()
            : base("name=COOKSGRAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<USER_ALLERGENS> USER_ALLERGENS { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<ALLERGENS> ALLERGENS { get; set; }
        public DbSet<RECIPE_ITEMS> RECIPE_ITEMS { get; set; }
        public DbSet<RECIPE_STEP> RECIPE_STEP { get; set; }
        public DbSet<RECIPES> RECIPES { get; set; }
        public DbSet<vv_AllRecipes> vv_AllRecipes { get; set; }
        public DbSet<VV_RECIPES> VV_RECIPES { get; set; }
    }
}
