//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezgıelıfproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_ITEMS
    {
        public int ID { get; set; }
        public int RECIPE_ID { get; set; }
        public string RECIPE_MEMBER { get; set; }
        public string RECIPE_MEMBERDESC { get; set; }
        public decimal RECIPE_MEMBER_RATIO { get; set; }
        public string RECIPE_MEMBER_RATIOUNIT { get; set; }
        public int RECIPE_MEMBER_ALLERGEN_ID { get; set; }
        public int RECIPE_ITEM_NUMBER { get; set; }
        public string RECIPE_ITEM_CREATEDBY { get; set; }
        public System.DateTime RECIPE_ITEM_LOGDATETIME { get; set; }
    }
}
