//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ezgıelıfproje
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPES
    {
        public int ID { get; set; }
        public string RECIPE_TYPE { get; set; }
        public string RECIPE_NAME { get; set; }
        public string RECIPE_DESCRIPTION { get; set; }
        public int RECIPE_PERSON { get; set; }
        public string RECIPE_CREATEDBY { get; set; }
        public string RECIPE_LOGDATETIME { get; set; }
    }
}
